export const LANGUAGE = {
    TR: {
        'Metamask ile bağlanmak için tıklayınız':'Metamask ile bağlanmak için tıklayınız',
        'Lüffen Email Adresi ve İsim Alanını  Boş Bırakmayınız':'Lüffen Email Adresi ve İsim Alanını  Boş Bırakmayınız',
        'Lütfen Geçerli Bir Değer Giriniz!':'Lütfen Geçerli Bir Değer Giriniz!',
        'Alacağınız toplam CYCE miktarı':'Alacağınız toplam CYCE miktarı',
        'İşlem yapmak için Bakiyeniz Yetersizdir.':'İşlem yapmak için Bakiyeniz Yetersizdir.',
        'Transfer Maliyeti Düştükten Sonra Alacağınız toplam CYCE miktarı':'Transfer Maliyeti Düştükten Sonra Alacağınız toplam CYCE miktarı',
        'Bağlantıyı Kes':'Bağlantıyı Kes',
        'Cüzdana Ekle':'Cüzdana Ekle',
        'Tüm Bakiyeniz İle CYCE Almak İçin Bu Butona Tıklayınız':'Tüm Bakiyeniz İle CYCE Almak İçin Bu Butona Tıklayınız',
        'CYCE Bakiyeniz':'CYCE Bakiyeniz',
        '1 Ay':'1 Ay',
        'CYCE Al':'CYCE Al',
        'Ethereum Bakiyeniz':'Ethereum Bakiyeniz',
        '28 Mayıs 2021':'28 Mayıs 2021',
        'Özel Satış(Private Sale)' :'Özel Satış(Private Sale)',
        'İşleminiz onaylandı': 'İşleminiz onaylandı',
        'CYCE Dönüştürme': 'CYCE Dönüştürme',
        'Cüzdan Numaranız:': 'Cüzdan Numaranız:',
        'CYCE Sözleşme Adresi:': 'CYCE Sözleşme Adresi:',
        'Lütfen almak istediğiniz CYCE miktarını girin(İşlem Ücretleri Mevcut Ethereum Bakiyenizden Düşecektir)': 'Lütfen almak istediğiniz CYCE miktarını girin(İşlem Ücretleri Mevcut Ethereum Bakiyenizden Düşecektir)',
        'İsim Giriniz': 'İsim Giriniz',
        'Mail Giriniz': 'Mail Giriniz',
        'Cüzdana Bağlan': 'Cüzdana Bağlan',
        'Siteye Geri Dön': 'Siteye Geri Dön',
        'Satış Başlangıç Tarihi': 'Satış Başlangıç Tarihi',
        'Satılacak CYCE Miktarı': 'Satılacak CYCE Miktarı',
        'Satılan CYCE Miktarı': 'Satılan CYCE Miktarı',
        'Bir Sonraki Adım': 'Bir Sonraki Adım',
        'CYCE Fiyatı': 'CYCE Fiyatı',
        'ETH/USDT': 'ETH/USDT',
        'Satılan Miktar :': 'Satılan Miktar :',
        'Satış Süresi: 1 Ay': 'Satış Süresi: 1 Ay',
        'Tüm Alımları Görmek İçin Tıklayın.': 'Tüm Alımları Görmek İçin Tıklayın.',
    },
    EN: {
        'Metamask ile bağlanmak için tıklayınız':'Click to connect with Metamask',
        'Lüffen Email Adresi ve İsim Alanını  Boş Bırakmayınız':'Please do not leave the Email Address and Name Field blank',
        'Lütfen Geçerli Bir Değer Giriniz!':'Please Enter a Valid Value!',
        'Alacağınız toplam CYCE miktarı':'Total amount of CYCE you will receive',
        'İşlem yapmak için Bakiyeniz Yetersizdir.':'Insufficient Balance to Transact',
        'Transfer Maliyeti Düştükten Sonra Alacağınız toplam CYCE miktarı':'Total CYCE You Will Get After Deducting Transfer Cost',
        'Bağlantıyı Kes':'Disconnect',
        'Cüzdana Ekle':'Add to Wallet',
        'Tüm Bakiyeniz İle CYCE Almak İçin Bu Butona Tıklayınız':'Click This Button To Get CYCE With All Your Balance',
        'CYCE Bakiyeniz':'Your CYCE Balance',
        '1 Ay':'1 Month',
        'CYCE Al':'Get CYCE',
        'Ethereum Bakiyeniz':'Your Ethereum Balance',
        '28 Mayıs 2021':'28 May 2021',
        'Özel Satış(Private Sale)' :'Private Sale',
        'İşleminiz onaylandı': 'Your transaction has been confirmed',
        'CYCE Dönüştürme': 'CYCE Converter',
        'Cüzdan Numaranız:': 'Your Wallet Adress:',
        'CYCE Sözleşme Adresi:': 'CYCE Contract Adress:',
        'Lütfen almak istediğiniz CYCE miktarını girin(İşlem Ücretleri Mevcut Ethereum Bakiyenizden Düşecektir)': 'Please enter the amount of CYCE you want to receive. (Transaction Fees Will Deduct From Your Current Ethereum Balance)',
        'İsim Giriniz': 'Enter A Name',
        'Mail Giriniz': 'Enter Your Mail',
        'Cüzdana Bağlan': 'Connect to Wallet',
        'Siteye Geri Dön': 'Back to Site',
        'Satış Başlangıç Tarihi': ' Sale Start Date',
        'Satılacak CYCE Miktarı': 'CYCE Amount to be Sold',
        'Satılan CYCE Miktarı': 'Amount of CYCE Sold',
        'Bir Sonraki Adım': 'Next Step',
        'CYCE Fiyatı': 'CYCE Price',
        'ETH/USDT': 'ETH/USDT',
        'Satılan Miktar :': 'Quantity Sold :',
        'Satış Süresi: 1 Ay': 'Sale Period: 1 Month',
        'Tüm Alımları Görmek İçin Tıklayın.': 'Click To See All Purchases.',
    }
}
