export const LANGUAGE = {
    TR: {
        'İşleminiz onaylandı.': 'İşleminiz onaylandı.',
        'İşleminiz devam ediyor....': 'İşleminiz devam ediyor....',
        'Adınızı Giriniz..': 'Adınızı Giriniz..',
        'Mail Adresinizi Giriniz..': 'Mail Adresinizi Giriniz..',
        'Alacağınız CYCE Miktarı': 'Alacağınız CYCE Miktarı',
        'Ethereum Miktarını Giriniz.': 'Ethereum Miktarını Giriniz.',
        'Metamask ile bağlanmak için tıklayınız': 'Metamask ile bağlanmak için tıklayınız',
        'Lüffen Email Adresi ve İsim Alanını  Boş Bırakmayınız': 'Lüffen Email Adresi ve İsim Alanını  Boş Bırakmayınız',
        'Lütfen Geçerli Bir Değer Giriniz!': 'Lütfen Geçerli Bir Değer Giriniz!',
        'Alacağınız toplam CYCE miktarı': 'Alacağınız toplam CYCE miktarı',
        'İşlem yapmak için Bakiyeniz Yetersizdir.': 'İşlem yapmak için Bakiyeniz Yetersizdir.',
        'Transfer Maliyeti Düştükten Sonra Alacağınız toplam CYCE miktarı': 'Transfer Maliyeti Düştükten Sonra Alacağınız toplam CYCE miktarı',
        'Bağlantıyı Kes': 'Bağlantıyı Kes',
        'Cüzdana Ekle': 'Cüzdana Ekle',
        'Tüm Bakiyeniz İle CYCE Almak İçin Bu Butona Tıklayınız': 'Tüm Bakiyeniz İle CYCE Almak İçin Bu Butona Tıklayınız',
        'CYCE Bakiyeniz': 'CYCE Bakiyeniz',
        '1 Ay': '1 Ay',
        'CYCE Al': 'CYCE Al',
        'Ethereum Bakiyeniz': 'Ethereum Bakiyeniz',
        '28 Mayıs 2021': '28 Mayıs 2021',
        'Özel Satış(Private Sale)': 'Özel Satış(Private Sale)',
        'İşleminiz onaylandı': 'İşleminiz onaylandı',
        'CYCE Dönüştürme': 'CYCE Dönüştürme',
        'Cüzdan Numaranız:': 'Cüzdan Numaranız:',
        'CYCE Sözleşme Adresi:': 'CYCE Sözleşme Adresi:',
        'Lütfen almak istediğiniz CYCE miktarını girin(İşlem Ücretleri Mevcut Ethereum Bakiyenizden Düşecektir)': 'Lütfen almak istediğiniz CYCE miktarını girin(İşlem Ücretleri Mevcut Ethereum Bakiyenizden Düşecektir)',
        'İsim Giriniz': 'İsim Giriniz',
        'Mail Giriniz': 'Mail Giriniz',
        'Cüzdana Bağlan': 'Cüzdana Bağlan',
        'Siteye Geri Dön': 'Siteye Geri Dön',
        'Satış Başlangıç Tarihi': 'Özel Satış Başlangıç Tarihi',
        'Satılacak CYCE Miktarı': 'ICO Satış  Miktarı',
        'Satılan CYCE Miktarı': 'Satılan CYCE Miktarı',
        'Bir Sonraki Adım': 'Bir Sonraki Adım',
        'CYCE Fiyatı': 'CYCE Fiyatı',
        'ETH/USDT': 'ETH/USDT',
        'Satılan Miktar :': 'Satılan Miktar :',
        'Satış Süresi: 1 Ay': 'Satış Süresi: 1 Ay',
        'Tüm Alımları Görmek İçin Tıklayın.': 'Tüm Alımları Görmek İçin Tıklayın.',
    },
    EN: {
        'İşleminiz onaylandı.': 'Your transaction has been confirmed.',
        'İşleminiz devam ediyor....': 'Your transaction is in progress..',
        'Adınızı Giriniz..': 'Enter Your Name..',
        'Mail Adresinizi Giriniz..': 'Enter Your Email..',
        'Alacağınız CYCE Miktarı': 'Enter the amount of CYCE you will receive..',
        'Ethereum Miktarını Giriniz.': 'Enter amount of ethereum..',
        'Metamask ile bağlanmak için tıklayınız': 'Click to connect with Metamask',
        'Lüffen Email Adresi ve İsim Alanını  Boş Bırakmayınız': 'Please do not leave the Email Address and Name Field blank',
        'Lütfen Geçerli Bir Değer Giriniz!': 'Please Enter a Valid Value!',
        'Alacağınız toplam CYCE miktarı': 'Total amount of CYCE you will receive',
        'İşlem yapmak için Bakiyeniz Yetersizdir.': 'Insufficient Balance to Transact',
        'Transfer Maliyeti Düştükten Sonra Alacağınız toplam CYCE miktarı': 'Total CYCE You Will Get After Deducting Transfer Cost',
        'Bağlantıyı Kes': 'Disconnect',
        'Cüzdana Ekle': 'Add to Wallet',
        'Tüm Bakiyeniz İle CYCE Almak İçin Bu Butona Tıklayınız': 'Click This Button To Get CYCE With All Your Balance',
        'CYCE Bakiyeniz': 'Your CYCE Balance',
        '1 Ay': '1 Month',
        'CYCE Al': 'Get CYCE',
        'Ethereum Bakiyeniz': 'Your Ethereum Balance',
        '28 Mayıs 2021': '28 May 2021',
        'Özel Satış(Private Sale)': 'Private Sale',
        'İşleminiz onaylandı': 'Your transaction has been confirmed',
        'CYCE Dönüştürme': 'CYCE Converter',
        'Cüzdan Numaranız:': 'Your Wallet Adress:',
        'CYCE Sözleşme Adresi:': 'CYCE Contract Adress:',
        'Lütfen almak istediğiniz CYCE miktarını girin(İşlem Ücretleri Mevcut Ethereum Bakiyenizden Düşecektir)': 'Please enter the amount of CYCE you want to receive. (Transaction Fees Will Deduct From Your Current Ethereum Balance)',
        'İsim Giriniz': 'Enter A Name',
        'Mail Giriniz': 'Enter Your Mail',
        'Cüzdana Bağlan': 'Connect to Wallet',
        'Siteye Geri Dön': 'Back to Site',
        'Satış Başlangıç Tarihi': ' Private Sale Start Date',
        'Satılacak CYCE Miktarı': 'ICO  Amount to be Sold',
        'Satılan CYCE Miktarı': 'Amount of CYCE Sold',
        'Bir Sonraki Adım': 'Next Step',
        'CYCE Fiyatı': 'CYCE Price',
        'ETH/USDT': 'ETH/USDT',
        'Satılan Miktar :': 'Quantity Sold :',
        'Satış Süresi: 1 Ay': 'Sale Period: 1 Month',
        'Tüm Alımları Görmek İçin Tıklayın.': 'Click To See All Purchases.',
    },
    RU: {
        'İşleminiz onaylandı.': 'Ваша транзакция подтверждена.',
        'İşleminiz devam ediyor....': 'Ваша транзакция выполняется.',
        'Adınızı Giriniz..': 'Введите ваше имя..',
        'Mail Adresinizi Giriniz..': 'Введите ваш адрес электронной почты..',
        'Alacağınız CYCE Miktarı': 'Количество CYCE, которую вы получите.',
        'Ethereum Miktarını Giriniz.': ' Введите сумму  Ethereum.',
        'Metamask ile bağlanmak için tıklayınız': 'Нажмите, чтобы подключиться к Metamask',
        'Lüffen Email Adresi ve İsim Alanını  Boş Bırakmayınız': "Пожалуйста, не оставляйте адрес электронной почты и поле имени пустыми",
        'Alacağınız toplam CYCE miktarı': " Общая количество CYCE, которую вы получите ",
        'İşlem yapmak için Bakiyeniz Yetersizdir.': 'На вашем балансе недостаточно средств для совершения транзакции',
        'Transfer Maliyeti Düştükten Sonra Alacağınız toplam CYCE miktarı': 'Общая сумма CYCE, которую вы получите после вычета стоимости трансфера',
        'Bağlantıyı Kes': 'Отключить',
        'Cüzdana Ekle': "Добавить в кошелек",
        'Tüm Bakiyeniz İle CYCE Almak İçin Bu Butona Tıklayınız': "Нажмите на эту кнопку, чтобы получить CYCE со всем вашим балансом",
        'CYCE Bakiyeniz': "Ваш CYCE баланс ",
        '1 Ay': '1 МЕСЯЦ',
        'CYCE Al': ' Купить CYCE ',
        'Ethereum Bakiyeniz': ' Ваш Ethereum баланс',
        '28 Mayıs 2021': '28 Maя 2021',
        'Özel Satış(Private Sale)': 'Частная Продажа (Private Sale)',
        'İşleminiz onaylandı': 'Ваша транзакция подтверждена.',
        'CYCE Dönüştürme': ' Преобразование в CYCE ',
        'Cüzdan Numaranız:': ' Номер вашего кошелька:',
        'CYCE Sözleşme Adresi:': 'Адрес контракта CYCE:',
        'Lütfen almak istediğiniz CYCE miktarını girin(İşlem Ücretleri Mevcut Ethereum Bakiyenizden Düşecektir)': 'Введите сумму CYCE, которую вы хотите получить (Комиссия за транзакцию будет вычтена из вашего текущего баланса Ethereum)',
        'İsim Giriniz': 'Введите имя',
        'Mail Giriniz': 'Введите адрес электронной почты',
        'Cüzdana Bağlan': "Подключиться к кошельку",
        'Siteye Geri Dön': 'Вернуться на сайт',
        'Satış Başlangıç Tarihi': "Дата начала продаж",

        'Özel Satış Başlangıç Tarihi': "Дата начала специальной распродажи",

        'Satılacak CYCE Miktarı': 'Количество CYCE для продажи',
        'ICO Satış  Miktarı': 'Объем продаж ICO',
        'Satılan CYCE Miktarı': "Количество проданного СYCE",
        'Bir Sonraki Adım': 'Следуюший шаг',
        'CYCE Fiyatı': ' Цена CYCE ',
        'ETH/USDT': 'ETH/USDT',
        'Satılan Miktar :': 'Проданная количество:',
        'Satış Süresi: 1 Ay': "Время Продажи: 1 Месяц",
        'Tüm Alımları Görmek İçin Tıklayın.': 'Нажмите, Чтобы Увидеть Все Покупки.',
    }

}
